name: NightlyBuild

on:
  schedule:
  - cron: "0 18 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: self-hosted
    
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push docker images
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin 
          tag=nightly-$(date '+%Y%m%d')
          chmod -R 755 hack/
          docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile . --push --tag docker.io/zxs943023403/http-demo:${tag}